import { useState, useEffect, useRef } from 'react';
import { 
  Box, 
  Button, 
  TextField, 
  Typography, 
  Tabs,
  Tab,
  Paper,
  Snackbar,
  Alert,
  Checkbox,
  IconButton
} from '@mui/material';
import PlayArrowIcon from '@mui/icons-material/PlayArrow';
import PauseIcon from '@mui/icons-material/Pause';
import SkipNextIcon from '@mui/icons-material/SkipNext';
import SkipPreviousIcon from '@mui/icons-material/SkipPrevious';

// Components
import AudioPlayer from '../components/AudioPlayer';
import ContextTimeline from '../components/ContextTimeline';
import DebugPanel from '../components/DebugPanel';
import PromptEditor from '../components/PromptEditor';
import StatusIndicator, { LoadingIndicator } from '../components/StatusIndicator';
import TopicsList from '../components/TopicsList';
import TranscriptView from '../components/TranscriptView';

// Hooks
import useSSEConnection from '../hooks/useSSEConnection';

// Utils
import { createLogger } from '../utils/logUtils';

export default function Home() {
  // State
  const [audioUrl, setAudioUrl] = useState('');
  const [contextSegments, setContextSegments] = useState([]);
  const [logs, setLogs] = useState([]);
  const [currentTab, setCurrentTab] = useState(0);
  const [promptConfig, setPromptConfig] = useState({ 
    contextPrompt: "", 
    mainTopicInstruction: "" 
  });
  const [playbackStarted, setPlaybackStarted] = useState(false);
  const [processingStatus, setProcessingStatus] = useState('idle');
  const [statusMessage, setStatusMessage] = useState('');
  const [errorMessage, setErrorMessage] = useState('');
  const [showError, setShowError] = useState(false);
  const [summary, setSummary] = useState('');
  const [topTopics, setTopTopics] = useState([]);
  const [debugModeEnabled, setDebugModeEnabled] = useState(true);
  const [isPaused, setIsPaused] = useState(true);
  const [currentTime, setCurrentTime] = useState(0);
  
  // Refs
  const audioRef = useRef(null);
  const currentSegmentRef = useRef(-1);
  const eventSourceRef = useRef(null);
  const timerRef = useRef(null);
  const connectionSetupRef = useRef(false);
  
  // Create logger
  const logger = (message) => {
    console.log(message);
    setLogs(prev => [...prev, `${new Date().toISOString().substring(11, 19)} - ${message}`]);
  };
  
  // Process status update
  const handleStatusUpdate = (data) => {
    setProcessingStatus(data.status);
    setStatusMessage(data.message);
    
    if (data.status === 'error' && data.error) {
      setErrorMessage(data.error);
      setShowError(true);
    }
  };
  
  // Handle error
  const handleError = (data) => {
    logger(`Error: ${data.message || 'Unknown error'}`);
    setErrorMessage(data.message || 'An unknown error occurred');
    setShowError(true);
    setProcessingStatus('error');
  };
  
  // Define the mock data generator function
  const generateMockData = (segmentIndex) => {
    const mockData = {
      transcript: `Debug transcript at ${new Date().toISOString().substring(11, 19)}. This is segment ${segmentIndex}.`,
      context: `This is simulated context for debugging purposes. No API call was made to save costs. The content simulates what would be generated by an AI model analyzing the audio at time index ${segmentIndex * 15} seconds.`,
      wikipedia: segmentIndex % 3 === 0 ? { // Only add Wikipedia info to every 3rd segment
        title: "Podcast",
        url: "https://en.wikipedia.org/wiki/Podcast",
        snippet: "A podcast is an episodic series of digital audio files that a user can download or stream to listen to."
      } : null,
      segment: `15-second segment #${segmentIndex} (Debug Mode)`,
      timestamp: Date.now(),
      mainTopic: `Topic ${segmentIndex}`,
      segmentIndex
    };
    return mockData;
  };
  
  // Set up the SSE connection hook
  const sseConnection = useSSEConnection({
    onMessage: (data) => {
      logger(`Debug mock message: ${JSON.stringify(data).substring(0, 50)}...`);
    },
    onStatus: handleStatusUpdate,
    onError: handleError,
    onLog: (data) => logger(data.message || "Debug log event"),
    debugMode: debugModeEnabled,
    generateMockData,
    logger
  });
  
  // Calculate current segment based on audio time
  useEffect(() => {
    if (!playbackStarted) return;
    
    const segmentDuration = 15; // 15 seconds per segment
    const newSegmentIndex = Math.floor(currentTime / segmentDuration);
    
    if (newSegmentIndex !== currentSegmentRef.current) {
      currentSegmentRef.current = newSegmentIndex;
      logger(`Current segment changed to ${newSegmentIndex} (${currentTime}s)`);
    }
  }, [currentTime, playbackStarted]);
  
  // Update timer for current time
  useEffect(() => {
    if (!playbackStarted || !audioRef.current) return;
    
    const updateTimer = () => {
      if (audioRef.current && !isPaused) {
        setCurrentTime(audioRef.current.currentTime);
      }
    };
    
    // Update every 250ms
    timerRef.current = setInterval(updateTimer, 250);
    
    return () => {
      if (timerRef.current) {
        clearInterval(timerRef.current);
      }
    };
  }, [playbackStarted, isPaused]);
  
  // Set up audio events when audio element changes
  useEffect(() => {
    if (!audioRef.current) return;
    
    const handlePlay = () => {
      setIsPaused(false);
      logger("Audio playback started");
    };
    
    const handlePause = () => {
      setIsPaused(true);
      logger("Audio playback paused");
    };
    
    const handleTimeUpdate = () => {
      // This is handled by the interval timer for smoother updates
    };
    
    const handleError = (e) => {
      logger(`Audio error: ${e.target.error?.message || 'Unknown error'}`);
      setErrorMessage(`Failed to play audio: ${e.target.error?.message || 'The audio file could not be played'}`);
      setShowError(true);
      setIsPaused(true);
      setPlaybackStarted(false);
    };
    
    // Add event listeners
    audioRef.current.addEventListener('play', handlePlay);
    audioRef.current.addEventListener('pause', handlePause);
    audioRef.current.addEventListener('timeupdate', handleTimeUpdate);
    audioRef.current.addEventListener('error', handleError);
    
    // Clean up
    return () => {
      if (audioRef.current) {
        audioRef.current.removeEventListener('play', handlePlay);
        audioRef.current.removeEventListener('pause', handlePause);
        audioRef.current.removeEventListener('timeupdate', handleTimeUpdate);
        audioRef.current.removeEventListener('error', handleError);
      }
    };
  }, [audioRef.current]);
  
  // Load prompt configuration (dev only)
  useEffect(() => {
    if (process.env.NODE_ENV === 'development') {
      fetch('/api/get-prompt')
        .then(res => res.json())
        .then(data => {
          setPromptConfig(data);
          logger("Loaded prompt configuration");
        })
        .catch(err => {
          console.error("Failed to load prompt configuration:", err);
          logger("Failed to load prompt configuration");
        });
    }
  }, []);
  
  // Handler for receiving segment data
  const handleSegmentReceived = (segment) => {
    logger(`Received segment #${segment.segmentIndex} from server`);
    
    // Add segment to the timeline as it arrives
    setContextSegments(prev => {
      // Check if this segment already exists (by index)
      const existingIndex = prev.findIndex(s => s.segmentIndex === segment.segmentIndex);
      
      if (existingIndex >= 0) {
        // Replace existing segment
        const updated = [...prev];
        updated[existingIndex] = segment;
        logger(`Updated existing segment #${segment.segmentIndex}`);
        return updated;
      } else {
        // Add new segment
        logger(`Adding new segment #${segment.segmentIndex} to timeline`);
        return [...prev, segment];
      }
    });
    
    // Update topics if needed
    if (segment.mainTopic) {
      updateTopTopics(segment.mainTopic);
      logger(`Updated topics with: ${segment.mainTopic}`);
    }
    
    // Generate summary if needed
    if ((contextSegments.length + 1) % 4 === 0) {
      logger(`Generating summary after ${contextSegments.length + 1} segments`);
      generateSummary();
    }
  };
  
  // Set up SSE connection when playback starts
  useEffect(() => {
    // Only run this effect when playback starts and we have a URL
    if (!playbackStarted || !audioUrl) return;
    
    // Prevent infinite loop by checking if we've already set up the connection
    if (connectionSetupRef.current) return;
    
    // Mark that we've set up the connection for this session
    connectionSetupRef.current = true;
    
    logger("Setting up SSE connection");
    
    // Close any existing connections first
    if (eventSourceRef.current) {
      eventSourceRef.current.close();
      eventSourceRef.current = null;
    }
    
    if (debugModeEnabled) {
      // Debug mode: Generate mock data directly with a timer
      logger("Setting up debug mode with direct timer");
      
      // Create the first segment immediately to show progress
      const firstSegment = generateMockData(0);
      setContextSegments([firstSegment]);
      updateTopTopics(firstSegment.mainTopic);
      logger("Created and added initial mock segment #0");
      
      // Set up a timer to generate new segments every 5 seconds
      let segmentIndex = 1;
      const mockTimer = setInterval(() => {
        logger(`Debug timer: Generating mock segment ${segmentIndex}`);
        const mockData = generateMockData(segmentIndex);
        handleSegmentReceived(mockData);
        segmentIndex++;
      }, 5000); // Every 5 seconds for testing
      
      // Store the timer in the ref so we can clear it later
      eventSourceRef.current = { 
        close: () => {
          logger("Clearing debug mode timer");
          clearInterval(mockTimer);
        } 
      };
      
      // Update status
      handleStatusUpdate({
        status: 'ready',
        message: 'Started mock data generation at 5-second intervals'
      });
    } else {
      // Non-debug mode: Set up real SSE connection
      logger("Setting up real SSE connection");
      
      // Make sure we're using a valid URL
      let processedUrl = audioUrl;
      
      // If it's a relative URL, convert it to absolute
      if (audioUrl.startsWith('/')) {
        processedUrl = window.location.origin + audioUrl;
        logger(`Converting relative URL to absolute: ${processedUrl}`);
      }
      
      const encodedUrl = encodeURIComponent(processedUrl);
      logger(`Encoded URL for API: ${encodedUrl}`);
      
      // Create a new EventSource with the encoded URL
      const sseUrl = `/api/stream?podcastUrl=${encodedUrl}`;
      logger(`Creating EventSource with URL: ${sseUrl}`);
      
      // Create the EventSource with proper error handling
      try {
        const eventSource = new EventSource(sseUrl);
        
        // Store the event source in the ref so we can close it later
        eventSourceRef.current = eventSource;
        
        // Set up event handlers
        eventSource.onopen = () => {
          logger("SSE connection opened successfully");
          
          // Send a status update to indicate the connection is ready
          handleStatusUpdate({
            status: 'ready',
            message: 'Connected to server, waiting for segments...'
          });
        };
        
        // Handle message events (transcript segments)
        eventSource.addEventListener('message', (event) => {
          try {
            logger(`Received message event: ${event.data.substring(0, 50)}...`);
            const data = JSON.parse(event.data);
            
            if (data.transcript) {
              logger(`Processing transcript segment #${data.segmentIndex}`);
              handleSegmentReceived(data);
            } else {
              logger(`Received non-transcript message: ${JSON.stringify(data).substring(0, 100)}...`);
            }
          } catch (err) {
            console.error('Error parsing SSE data:', err);
            logger(`Error parsing SSE data: ${err.message}`);
          }
        });
        
        // Handle status events
        eventSource.addEventListener('status', (event) => {
          try {
            const data = JSON.parse(event.data);
            logger(`Status update: ${data.status} - ${data.message}`);
            handleStatusUpdate(data);
            
            // If we get a "processing" status for a segment, log it
            if (data.status === 'processing' && data.message.includes('segment')) {
              logger(`Server is processing segment: ${data.message}`);
            }
          } catch (err) {
            console.error('Error parsing status event:', err);
            logger(`Error parsing status event: ${err.message}`);
          }
        });
        
        // Handle log events
        eventSource.addEventListener('log', (event) => {
          try {
            const data = JSON.parse(event.data);
            logger(`Server log: ${data.message || event.data}`);
          } catch (err) {
            logger(`Server raw log: ${event.data}`);
          }
        });
        
        // Handle errors
        eventSource.onerror = (err) => {
          console.error('EventSource error:', err);
          logger('SSE connection error occurred');
          
          if (eventSource.readyState === EventSource.CLOSED) {
            logger('SSE connection was closed');
          } else if (eventSource.readyState === EventSource.CONNECTING) {
            logger('SSE connection is reconnecting...');
          }
          
          handleError({ message: 'Connection to server lost or interrupted' });
        };
        
        // Log that we've set up the connection
        logger("Real SSE connection established and event handlers set up");
      } catch (err) {
        logger(`Error setting up SSE connection: ${err.message}`);
        handleError({ message: `Failed to connect to server: ${err.message}` });
      }
    }
    
    // This cleanup function will only run when playbackStarted becomes false
    // or when the component unmounts
    return () => {
      if (eventSourceRef.current) {
        logger("Cleaning up SSE connection");
        eventSourceRef.current.close();
        eventSourceRef.current = null;
        logger("Closed SSE connection on cleanup");
      }
    };
  }, [playbackStarted]); // Only depend on playbackStarted to prevent unnecessary re-runs
  
  // Update top topics
  const updateTopTopics = (newTopic) => {
    setTopTopics(prev => {
      // Check if topic exists
      const existingIndex = prev.findIndex(item => item.topic === newTopic);
      
      if (existingIndex >= 0) {
        // Update existing topic
        const updated = [...prev];
        updated[existingIndex] = {
          ...updated[existingIndex],
          count: updated[existingIndex].count + 1
        };
        
        // Sort by count
        return updated.sort((a, b) => b.count - a.count);
      } else {
        // Add new topic
        const updated = [...prev, { topic: newTopic, count: 1 }];
        
        // Sort and limit to top 5
        return updated.sort((a, b) => b.count - a.count).slice(0, 5);
      }
    });
  };
  
  // Generate summary
  const generateSummary = async () => {
    if (contextSegments.length < 4) return;
    
    // Skip API call in debug mode
    if (debugModeEnabled) {
      logger("Debug mode: Skipping summary generation API call");
      setSummary("This is a debug summary. Real API call was skipped to reduce costs.");
      return;
    }
    
    try {
      const recentSegments = contextSegments.slice(-4);
      const combinedTranscript = recentSegments.map(s => s.transcript).join(' ');
      
      const response = await fetch('/api/transcribe', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: combinedTranscript, summarize: true })
      });
      
      if (response.ok) {
        const data = await response.json();
        setSummary(data.context || 'No summary available.');
        logger("Summary generated successfully");
      }
    } catch (error) {
      logger(`Error generating summary: ${error.message}`);
    }
  };
  
  // Close existing connections
  const closeConnections = () => {
    if (eventSourceRef.current) {
      eventSourceRef.current.close();
      eventSourceRef.current = null;
      logger("Closed SSE connection");
    }
    
    if (timerRef.current) {
      clearInterval(timerRef.current);
      timerRef.current = null;
    }
  };
  
  // URL validation function
  const isValidUrl = (string) => {
    try {
      new URL(string);
      return true;
    } catch (_) {
      return false;
    }
  };
  
  // Start processing podcast
  const startProcessing = () => {
    if (!audioUrl) {
      setErrorMessage("Please enter a podcast URL");
      setShowError(true);
      logger("No URL provided");
      return;
    }
    
    if (!isValidUrl(audioUrl)) {
      setErrorMessage("Please enter a valid URL");
      setShowError(true);
      logger("Invalid URL format");
      return;
    }
    
    // Close any existing connections
    closeConnections();
    
    // Reset state
    setContextSegments([]);
    setSummary('');
    setTopTopics([]);
    setProcessingStatus('initializing');
    setStatusMessage('Starting audio processing...');
    currentSegmentRef.current = -1;
    setCurrentTime(0);
    
    // Reset connection setup flag to allow a new connection
    connectionSetupRef.current = false;
    
    logger(`Starting processing for URL: ${audioUrl}`);
    
    // Set up audio element for direct playing
    if (audioRef.current) {
      audioRef.current.src = audioUrl;
      audioRef.current.crossOrigin = "anonymous"; // Enable CORS
      audioRef.current.currentTime = 0;
      logger("Audio element source set");
    }
    
    // Set playback started - this will trigger the useEffect that sets up the SSE connection
    setPlaybackStarted(true);
    
    // Try to play audio immediately
    setTimeout(() => {
      if (audioRef.current) {
        audioRef.current.play()
          .then(() => {
            logger("Audio playback started via direct play");
            setIsPaused(false);
          })
          .catch(err => {
            logger(`Error starting audio: ${err.message}. User may need to click play.`);
            setIsPaused(true);
          });
      }
    }, 1000); // Give a short delay to ensure UI has updated
  };
  
  // Handle tab change
  const handleTabChange = (event, newValue) => {
    setCurrentTab(newValue);
  };
  
  // Jump to segment
  const jumpToSegment = (index) => {
    if (audioRef.current && index >= 0 && index < contextSegments.length) {
      // Estimate time based on segment index
      const estimatedTime = index * 15; // 15 seconds per segment
      audioRef.current.currentTime = estimatedTime;
      setCurrentTime(estimatedTime);
      currentSegmentRef.current = index;
      logger(`Jumped to segment ${index} (time: ${estimatedTime}s)`);
    }
  };
  
  // Play/pause controls
  const togglePlayPause = () => {
    if (audioRef.current) {
      if (isPaused) {
        audioRef.current.play()
          .then(() => logger("Playback resumed"))
          .catch(err => logger(`Play error: ${err.message}`));
      } else {
        audioRef.current.pause();
        logger("Playback paused");
      }
    }
  };
  
  const skipForward = (seconds = 15) => {
    if (audioRef.current) {
      audioRef.current.currentTime += seconds;
      setCurrentTime(audioRef.current.currentTime);
      logger(`Skipped forward ${seconds} seconds`);
    }
  };
  
  const skipBackward = (seconds = 15) => {
    if (audioRef.current) {
      audioRef.current.currentTime = Math.max(0, audioRef.current.currentTime - seconds);
      setCurrentTime(audioRef.current.currentTime);
      logger(`Skipped backward ${seconds} seconds`);
    }
  };
  
  // Save prompt configuration
  const savePromptConfig = async () => {
    try {
      const res = await fetch('/api/update-prompt', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(promptConfig),
      });
      
      const data = await res.json();
      logger("Prompt configuration updated");
    } catch (err) {
      console.error("Error updating prompt config:", err);
      logger(`Error updating prompt config: ${err.message}`);
    }
  };
  
  // Toggle debug mode
  const toggleDebugMode = (enabled) => {
    setDebugModeEnabled(enabled);
    logger(`Debug mode ${enabled ? 'enabled' : 'disabled'}`);
  };
  
  // Stop playback
  const stopPlayback = () => {
    if (audioRef.current) {
      audioRef.current.pause();
    }
    
    // Close any existing connections
    closeConnections();
    
    // Reset state
    setPlaybackStarted(false);
    setIsPaused(true);
    logger("Playback stopped by user");
  };
  
  // Format time for display
  const formatTime = (seconds) => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };
  
  // Clean up on unmount or page refresh
  useEffect(() => {
    // Add beforeunload event listener to handle page refresh
    const handleBeforeUnload = () => {
      closeConnections();
      logger("Page unloading - closing connections");
    };
    
    window.addEventListener('beforeunload', handleBeforeUnload);
    
    // Clean up on component unmount
    return () => {
      window.removeEventListener('beforeunload', handleBeforeUnload);
      closeConnections();
      logger("Component unmounting - closing connections");
    };
  }, []);
  
  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', height: '100vh', bgcolor: '#f5f5f7' }}>
      {/* Header */}
      <Box sx={{ p: 2, bgcolor: '#fff', boxShadow: 1 }}>
        <Typography variant="h4" gutterBottom sx={{ fontWeight: 'bold', color: '#333' }}>
          Podcast Context Assistant
        </Typography>
        <Typography variant="body2" color="text.secondary" gutterBottom>
          Listen to podcasts with real-time AI-generated context
        </Typography>
      </Box>
      
      {/* Main content */}
      <Box sx={{ display: 'flex', flexGrow: 1, p: 2, overflow: 'hidden' }}>
        {/* Left Panel: Audio URL Input & Player */}
        <Box sx={{ flex: '0 0 350px', p: 2, mr: 2, bgcolor: '#fff', borderRadius: 2, boxShadow: 1 }}>
          <Typography variant="h6" gutterBottom>Podcast Audio</Typography>
          
          <TextField
            fullWidth
            label="Podcast URL (MP3, WAV, or Spotify)"
            variant="outlined"
            value={audioUrl}
            onChange={(e) => setAudioUrl(e.target.value)}
            sx={{ mb: 2 }}
          />
          
          {/* Debug mode toggle */}
          <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
            <Checkbox
              checked={debugModeEnabled}
              onChange={(e) => toggleDebugMode(e.target.checked)}
            />
            <Typography variant="body2" color="text.secondary">
              Debug mode (reduces API usage)
            </Typography>
          </Box>
          
          {/* Start/Stop button with loading indicator */}
          <Button 
            variant="contained" 
            onClick={playbackStarted ? stopPlayback : startProcessing}
            sx={{ 
              mb: 2, 
              width: '100%',
              bgcolor: playbackStarted && !isPaused ? '#f44336' : '#1976d2',
              '&:hover': {
                bgcolor: playbackStarted && !isPaused ? '#d32f2f' : '#1565c0',
              }
            }}
            disabled={
              processingStatus === 'initializing' || 
              processingStatus === 'processing'
            }
          >
            {(processingStatus === 'initializing' || processingStatus === 'processing') ? (
              <>
                <LoadingIndicator loading={true} />
              </>
            ) : (
              playbackStarted && !isPaused ? 'Stop Playback' : 'Start Listening'
            )}
          </Button>
          
          {/* Status indicator */}
          <StatusIndicator 
            status={processingStatus}
            message={statusMessage}
            visible={processingStatus !== 'idle'}
          />
          
          {/* Audio player */}
          {playbackStarted && (
            <>
              {/* Use the AudioPlayer component */}
              <AudioPlayer 
                audioUrl={audioUrl}
                segmentTiming={{
                  isPaused,
                  isBuffering: false,
                  registerAudioElement: (audio) => {
                    audioRef.current = audio;
                  },
                  togglePlayPause,
                  skipForward,
                  skipBackward,
                  audioRef
                }}
                visible={true}
              />
              
              {/* Current time display */}
              <Typography textAlign="center" variant="body2" color="text.secondary" gutterBottom>
                {formatTime(currentTime)}
              </Typography>
              
              {/* Topic overview */}
              <TopicsList 
                topics={topTopics}
                visible={topTopics.length > 0}
              />
              
              {/* Summary */}
              {summary && (
                <Box sx={{ mb: 2 }}>
                  <Typography variant="subtitle1" gutterBottom>Recent Summary</Typography>
                  <Typography variant="body2">{summary}</Typography>
                </Box>
              )}
            </>
          )}
          
          {/* Prompt editor (dev only) */}
          <PromptEditor
            promptConfig={promptConfig}
            onConfigChange={setPromptConfig}
            onSave={savePromptConfig}
          />
        </Box>
        
        {/* Right Panel: Context Timeline, Transcript, and Debug Info */}
        <Box sx={{ 
          flex: 1, 
          display: 'flex', 
          flexDirection: 'column',
          overflow: 'hidden', 
          bgcolor: '#fff', 
          borderRadius: 2,
          boxShadow: 1
        }}>
          <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
            <Tabs value={currentTab} onChange={handleTabChange}>
              <Tab label="Timeline" />
              <Tab label="Transcript" />
              <Tab label="Debug" />
            </Tabs>
          </Box>
          
          {/* Timeline Tab */}
          <Box 
            role="tabpanel"
            hidden={currentTab !== 0}
            sx={{ flexGrow: 1, overflow: 'auto', p: 2 }}
          >
            <ContextTimeline
              segments={contextSegments}
              currentSegmentIndex={currentSegmentRef.current}
              onSegmentClick={jumpToSegment}
            />
          </Box>
          
          {/* Transcript Tab */}
          <Box 
            role="tabpanel"
            hidden={currentTab !== 1}
            sx={{ flexGrow: 1, overflow: 'auto', p: 2 }}
          >
            <TranscriptView
              segments={contextSegments}
              currentSegmentIndex={currentSegmentRef.current}
              onSegmentClick={jumpToSegment}
            />
          </Box>
          
          {/* Debug Tab */}
          <Box 
            role="tabpanel"
            hidden={currentTab !== 2}
            sx={{ flexGrow: 1, overflow: 'auto', p: 2 }}
          >
            <DebugPanel logs={logs} />
          </Box>
        </Box>
      </Box>
      
      {/* Error Snackbar */}
      <Snackbar
        open={showError}
        autoHideDuration={6000}
        onClose={() => setShowError(false)}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      >
        <Alert 
          onClose={() => setShowError(false)} 
          severity="error" 
          sx={{ width: '100%' }}
        >
          {errorMessage}
        </Alert>
      </Snackbar>
    </Box>
  );
}
